---
# tasks file for roles/inventory-local
- name: Create inventory directory
  file:
    path: "{{workdir}}/inventory"
    state: directory

- name: Remove files if exists
  file: 
    path: "{{workdir}}/inventory/inventory-local"
    state: absent

- name: Create local inventory file
  template:
    src: local-inventory.j2
    dest: "{{workdir}}/inventory/inventory-local"
